### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat()J

### ISSUE THREAD

**Issue by LucasNask** [LucasNask/FingerPrintDetection#1]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat()J
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:26)
	at FingerPrintCore.FingerPrint.<init>(FingerPrint.java:12)
	at FingerPrintCore.FingerPrintTester.main(FingerPrintTester.java:19)

**Comment by KelvynSouza** [comment]
Não sei como te ajudar, procura no google.
